server:
  port: 8079
dubbo:
  application:
    name: user-service-provider
  registry:
    address: 101.132.97.99:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry